services:
  alfred:
    image: mysql:8.0
    container_name: alfred
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: alfred
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      timeout: 20s
      retries: 3
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financial-service
    depends_on:
      alfred:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      APP_URL: ${APP_URL}
      MYSQL_URL: ${MYSQL_URL}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SMTP_EMAIL: ${SMTP_EMAIL}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    volumes:
      - ./logs:/app/logs
    links:
      - alfred
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/ping" ] # Adapte a URL do seu health check
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
volumes:
  db_data: