spring:
  application:
    name: financial-auth
    url: ${APP_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jwt:
    secret: ${JWT_SECRET}
  smtp:
    email: ${SMTP_EMAIL}
    password: ${SMTP_PASSWORD}